# Generated by Django 4.1 on 2022-09-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=5000, null=True)),
                ('address', models.TextField(blank=True, max_length=300, null=True)),
                ('phone', models.TextField(blank=True, max_length=300, null=True)),
                ('mobile_phone', models.TextField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
