# Generated by Django 4.1 on 2022-11-01 14:39

from django.db import migrations, models
import django.db.models.deletion
import web.gallery.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Unknown', max_length=50, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='album_covers')),
                ('description', models.TextField(max_length=300)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(upload_to=web.gallery.models.scramble_uploaded_filename)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('album_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_set', to='gallery.album')),
            ],
        ),
    ]
