# Generated by Django 4.1 on 2022-09-01 11:13

from django.db import migrations, models
import web.gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_image_album_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='album_covers'),
        ),
        migrations.AddField(
            model_name='album',
            name='description',
            field=models.TextField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.ImageField(upload_to=web.gallery.models.scramble_uploaded_filename),
        ),
    ]
